import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useQuery } from "react-query";
import { Container } from "@mui/material";
import { useFetchUsers, useFilteredUsers } from "../hooks";
import { IUser } from "../ts";
import { GenderForm, Paginator, UserCard } from "../components";

export default function Home() {
  const { isLoading, error, data } = useQuery("users", useFetchUsers);
  const { filter, onPageChange, onFilterChange, filteredData } =
    useFilteredUsers(data);

  function renderContent() {
    if (isLoading) return <p>Loading...</p>;
    if (error) return <p>Error :(</p>;
    if (filteredData)
      return filteredData
        .slice(0, 10)
        .map((user: IUser) => <UserCard key={user.id} user={user} />);
  }

  return (
    <Container className={styles.container}>
      <Head>
        <title>Random User Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container className={styles.main}>
        <GenderForm onFilterChange={onFilterChange} filter={filter} />
        <Paginator filter={filter} onPageChange={onPageChange} />
        <Container className={styles.grid}>{renderContent()}</Container>
      </Container>
    </Container>
  );
}
